title: SGPE
description: Software de gestão e produção de planos de ensino utilizando o modelo de ensino de competências e habilidades.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
