title: Sigeplane
description: Sigeplane é um software de gestão e produção de planos de ensino utilizando o modelo de ensino por competências e habilidades.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
