spring:
    datasource:
        url     : jdbc:mysql://localhost:3306/sgpe?useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: pass12345
    flyway    :
        enabled: false
    jpa       :
        hibernate:
            ddl-auto: create
#        properties:
#            hibernate:
#                hbm2ddl:
#                    delimiter: ;
#            javax    :
#                persistence:
#                    schema-generation:
#                        create-source: metadata
#                        scripts      :
#                            action       : create
#                            create-target: SGPE_DDL.sql