spring:
    datasource:
        url     : jdbc:mysql://localhost:3306/sgpe?useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: pass12345
    flyway    :
        enabled: false
    jpa       :
        hibernate:
            ddl-auto: create