spring:
    jpa       :
        show-sql : true
        hibernate:
            ddl-auto: create
    flyway    :
        enabled: false
    h2        :
        console:
            enabled: true
    datasource:
        url              : jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driver-class-name: org.h2.Driver